import { INPUT_GROUPS, INPUTS } from './elements';
import type {
  ElementAttributeConfiguration,
  InputAttributeConfiguration,
  InputAttributes,
} from './types';

export const INPUT_ATTRIBUTES: InputAttributes = {
  accept: 'accept',
  autoFocus: 'autoFocus',
  defaultChecked: 'defaultChecked',
  defaultValue: 'defaultValue',
  description: 'description',
  disabled: 'disabled',
  disablePast: 'disablePast',
  falseValue: 'falseValue',
  format: 'format',
  id: 'id',
  interval: 'interval',
  label: 'label',
  max: 'max',
  maxRows: 'maxRows',
  min: 'min',
  minRows: 'minRows',
  multiple: 'multiple',
  name: 'name',
  options: 'options',
  placeholder: 'placeholder',
  prefix: 'prefix',
  readOnly: 'readOnly',
  required: 'required',
  row: 'row',
  size: 'size',
  suffix: 'suffix',
  tooltip: 'tooltip',
  trueValue: 'trueValue',
  variant: 'variant',
} as const;

export const INPUT_ATTRIBUTES_INPUT_MAP: InputAttributeConfiguration = {
  [INPUT_ATTRIBUTES.label]: {
    label: 'Label',
    placeholder: 'Label',
    inputType: INPUTS.singleLineText,
  },
  [INPUT_ATTRIBUTES.placeholder]: {
    label: 'Placeholder',
    placeholder: 'Placeholder',
    inputType: INPUTS.singleLineText,
  },
  [INPUT_ATTRIBUTES.description]: {
    label: 'Description',
    placeholder: 'Description',
    inputType: INPUTS.singleLineText,
  },
  [INPUT_ATTRIBUTES.disabled]: {
    label: 'Disabled',
    placeholder: '',
    inputType: INPUTS.switch,
  },
  [INPUT_ATTRIBUTES.readOnly]: {
    label: 'Read Only',
    placeholder: '',
    inputType: INPUTS.switch,
  },
  [INPUT_ATTRIBUTES.required]: {
    label: 'Required',
    placeholder: '',
    inputType: INPUTS.switch,
  },
  [INPUT_ATTRIBUTES.defaultValue]: {
    label: 'Default Value',
    placeholder: 'Default Value',
    inputType: INPUTS.singleLineText,
  },
  [INPUT_ATTRIBUTES.autoFocus]: {
    label: 'Auto Focus',
    placeholder: '',
    inputType: INPUTS.switch,
  },
  [INPUT_ATTRIBUTES.tooltip]: {
    label: 'Tooltip',
    placeholder: 'Tooltip',
    inputType: INPUTS.singleLineText,
  },
  [INPUT_ATTRIBUTES.prefix]: {
    label: 'Prefix',
    placeholder: 'Prefix',
    inputType: INPUTS.singleLineText,
  },
  [INPUT_ATTRIBUTES.suffix]: {
    label: 'Suffix',
    placeholder: 'Suffix',
    inputType: INPUTS.singleLineText,
  },
  [INPUT_ATTRIBUTES.options]: {
    label: 'Options',
    placeholder: 'Options',
    inputType: INPUTS.singleLineText,
  },
  [INPUT_ATTRIBUTES.id]: {
    label: 'ID',
    placeholder: 'ID',
    inputType: INPUTS.singleLineText,
  },
  [INPUT_ATTRIBUTES.name]: {
    label: 'Name',
    placeholder: 'Name',
    inputType: INPUTS.singleLineText,
  },
  [INPUT_ATTRIBUTES.defaultChecked]: {
    label: 'Default Checked',
    placeholder: '',
    inputType: INPUTS.switch,
  },
  [INPUT_ATTRIBUTES.variant]: {
    label: 'Variants',
    placeholder: '',
    inputType: INPUTS.radio,
    options: [
      {
        label: 'Default',
        value: 'default',
      },
      {
        label: 'Card',
        value: 'card',
      },
    ],
  },
  [INPUT_ATTRIBUTES.disablePast]: {
    label: 'Disable Past',
    placeholder: '',
    inputType: INPUTS.switch,
  },
  [INPUT_ATTRIBUTES.format]: {
    label: 'Format',
    placeholder: '',
    inputType: INPUTS.singleLineText,
  },
  [INPUT_ATTRIBUTES.interval]: {
    label: 'Interval',
    placeholder: '',
    inputType: INPUTS.singleLineText,
  },
  [INPUT_ATTRIBUTES.accept]: {
    label: 'Accept',
    placeholder: '',
    inputType: INPUTS.singleLineText,
  },
  [INPUT_ATTRIBUTES.multiple]: {
    label: 'Multiple',
    placeholder: '',
    inputType: INPUTS.switch,
  },
  [INPUT_ATTRIBUTES.max]: {
    label: 'Max',
    placeholder: '',
    inputType: INPUTS.number,
  },
  [INPUT_ATTRIBUTES.min]: {
    label: 'Min',
    placeholder: '',
    inputType: INPUTS.number,
  },
  [INPUT_ATTRIBUTES.size]: {
    label: 'Size',
    placeholder: '',
    inputType: INPUTS.number,
  },
  [INPUT_ATTRIBUTES.minRows]: {
    label: 'Min Rows',
    placeholder: '',
    inputType: INPUTS.number,
  },
  [INPUT_ATTRIBUTES.maxRows]: {
    label: 'Max Rows',
    placeholder: '',
    inputType: INPUTS.number,
  },
  [INPUT_ATTRIBUTES.trueValue]: {
    label: 'True Value',
    placeholder: '',
    inputType: INPUTS.singleLineText,
  },
  [INPUT_ATTRIBUTES.falseValue]: {
    label: 'False Value',
    placeholder: '',
    inputType: INPUTS.singleLineText,
  },
  [INPUT_ATTRIBUTES.row]: {
    label: 'Row layout',
    placeholder: '',
    inputType: INPUTS.switch,
  },
} as const;

export const INPUTS_ATTRIBUTES_MAP: ElementAttributeConfiguration = {
  [INPUTS.address]: [
    INPUT_ATTRIBUTES.autoFocus,
    INPUT_ATTRIBUTES.defaultValue,
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.placeholder,
    INPUT_ATTRIBUTES.readOnly,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.tooltip,
  ],
  [INPUTS.checkbox]: [
    INPUT_ATTRIBUTES.defaultChecked,
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.tooltip,
    INPUT_ATTRIBUTES.variant,
  ],
  [INPUTS.date]: [
    INPUT_ATTRIBUTES.defaultValue,
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.disablePast,
    INPUT_ATTRIBUTES.format,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.placeholder,
    INPUT_ATTRIBUTES.readOnly,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.tooltip,
  ],
  [INPUTS.datetime]: [
    INPUT_ATTRIBUTES.defaultValue,
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.disablePast,
    INPUT_ATTRIBUTES.format,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.interval,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.placeholder,
    INPUT_ATTRIBUTES.readOnly,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.tooltip,
  ],
  [INPUTS.email]: [
    INPUT_ATTRIBUTES.autoFocus,
    INPUT_ATTRIBUTES.defaultValue,
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.placeholder,
    INPUT_ATTRIBUTES.readOnly,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.tooltip,
  ],
  [INPUTS.file]: [
    INPUT_ATTRIBUTES.accept,
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.multiple,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.readOnly,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.size,
    INPUT_ATTRIBUTES.tooltip,
  ],
  [INPUTS.multiLineText]: [
    INPUT_ATTRIBUTES.autoFocus,
    INPUT_ATTRIBUTES.defaultValue,
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.maxRows,
    INPUT_ATTRIBUTES.minRows,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.placeholder,
    INPUT_ATTRIBUTES.readOnly,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.tooltip,
  ],
  [INPUTS.number]: [
    INPUT_ATTRIBUTES.autoFocus,
    INPUT_ATTRIBUTES.defaultValue,
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.max,
    INPUT_ATTRIBUTES.min,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.placeholder,
    INPUT_ATTRIBUTES.prefix,
    INPUT_ATTRIBUTES.readOnly,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.suffix,
    INPUT_ATTRIBUTES.tooltip,
  ],
  [INPUTS.password]: [
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.placeholder,
    INPUT_ATTRIBUTES.readOnly,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.tooltip,
  ],
  [INPUTS.phone]: [
    INPUT_ATTRIBUTES.autoFocus,
    INPUT_ATTRIBUTES.defaultValue,
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.placeholder,
    INPUT_ATTRIBUTES.prefix,
    INPUT_ATTRIBUTES.readOnly,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.tooltip,
  ],
  [INPUTS.radio]: [
    INPUT_ATTRIBUTES.defaultChecked,
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.tooltip,
    INPUT_ATTRIBUTES.variant,
  ],
  [INPUTS.richText]: [
    INPUT_ATTRIBUTES.defaultValue,
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.placeholder,
    INPUT_ATTRIBUTES.readOnly,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.tooltip,
  ],
  [INPUTS.select]: [
    INPUT_ATTRIBUTES.defaultValue,
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.multiple,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.options,
    INPUT_ATTRIBUTES.placeholder,
    INPUT_ATTRIBUTES.readOnly,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.tooltip,
  ],
  [INPUTS.singleLineText]: [
    INPUT_ATTRIBUTES.autoFocus,
    INPUT_ATTRIBUTES.defaultValue,
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.placeholder,
    INPUT_ATTRIBUTES.prefix,
    INPUT_ATTRIBUTES.readOnly,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.suffix,
    INPUT_ATTRIBUTES.tooltip,
  ],
  [INPUTS.switch]: [
    INPUT_ATTRIBUTES.defaultValue,
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.falseValue,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.readOnly,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.tooltip,
    INPUT_ATTRIBUTES.trueValue,
  ],
  [INPUTS.time]: [
    INPUT_ATTRIBUTES.defaultValue,
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.disablePast,
    INPUT_ATTRIBUTES.format,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.interval,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.placeholder,
    INPUT_ATTRIBUTES.readOnly,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.tooltip,
  ],
  [INPUTS.url]: [
    INPUT_ATTRIBUTES.autoFocus,
    INPUT_ATTRIBUTES.defaultValue,
    INPUT_ATTRIBUTES.description,
    INPUT_ATTRIBUTES.disabled,
    INPUT_ATTRIBUTES.id,
    INPUT_ATTRIBUTES.label,
    INPUT_ATTRIBUTES.name,
    INPUT_ATTRIBUTES.placeholder,
    INPUT_ATTRIBUTES.prefix,
    INPUT_ATTRIBUTES.readOnly,
    INPUT_ATTRIBUTES.required,
    INPUT_ATTRIBUTES.suffix,
    INPUT_ATTRIBUTES.tooltip,
  ],
  [INPUT_GROUPS.checkbox]: [],
  [INPUT_GROUPS.radio]: [],
} as const;
